### PR TITLE
Log and exit if we cannot get list of pods in a namespace

### PR DESCRIPTION
**Pull request by jpweber**
Fetch the list of pods is the first thing this has to do. If that fails let us know and just exit. No need to try doing work.

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
LGTM, please bump package version and you should release it/ and bump in `ap-airflow` repo.

**Review by andriisoldatenko — APPROVED** [review]

**Comment by jpweber** [comment]
@andriisoldatenko I can't find where I need to make the change in the `ap-airflow` repo, where/what file do I need to change there?

**Comment by andriisoldatenko** [comment]
https://github.com/astronomer/ap-airflow/blob/master/1.10.7/alpine3.10/Dockerfile#L93

**Review by sjmiller609 — COMMENTED** [review]
What is the difference in behavior here? this try / catch seems questionable to me because isn't the behavior without this change also non-zero return code and show error?

**Comment by jpweber** [comment]
Without this change it still will go through the loop, which it doesn't need to. But most importantly it will log an error if there is a problem requesting namespaces from the Kube API. Without this we'll just see it exit as if there weren't any namespaces.

**Comment by sjmiller609** [comment]
I'm having trouble with this explanation because it seems to me that if the 'except' block is ever called, it would be from and exception, and if there was an exception, it would not continue

**Comment by sjmiller609** [comment]
hmm unless there is a higher-level try except somewhere

EDIT: I don't see any such higher-level exception catching either 🤔

**Comment by jpweber** [comment]
If there is a better way to solve this I'm open to it. My "user story" here is  "If you make a call to a remote api, that can fail, log the error right away and exit since the rest of the work here depends on that call succeeding." I think this solves that, its right from the docs here https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_pod

Ultimately I don't care about the implementation, I care about answering my "user story" above.

**Comment by sjmiller609** [comment]
I think the only difference with this change is that now the error message has "Exception when calling CoreV1Api->list_namespaced_pod: " prepended to it.

What I mean is in the existing code version, this line:
```
pod_list = core_v1.list_namespaced_pod(namespace)
```
If it raises an exception "ApiException" (or any other exception)

It would not proceed to this loop:
```
for pod in pod_list.items:
  ...
```

For that reason, I think this change does not make any difference.

**Pull request closed without merging**
