### PR TITLE
Fix Flake8 violations

### PR DESCRIPTION
**Pull request by kaxil**
Master failed: https://circleci.com/gh/astronomer/astronomer-airflow-scripts/22

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
Doesn't look like a flake8 error to me, but okay.

**Comment by kaxil** [comment]
```
[#x1B[34m2020-11-18 12:15:46,697#x1B[0m] {#x1B[34mapplication.py:#x1B[0m297} INFO#x1B[0m - Reporting errors#x1B[0m
/home/circleci/project/astronomer/migration_spinner/command_line.py:34:36: F523 '...'.format(...) has unused arguments at position(s): 1
[#x1B[34m2020-11-18 12:15:46,698#x1B[0m] {#x1B[34mapplication.py:#x1B[0m303} INFO#x1B[0m - Found a total of 1 violations and reported 1#x1B[0m
```

**Review by ashb — CHANGES_REQUESTED** [review]
Yeah, the issue is two format args, but only one `{}`.

**Comment by kaxil** [comment]
Whoops yeah

**Review by ashb — APPROVED** [review]

**Pull request merged**
