### PR TITLE
Cleanup stuck pods

### PR DESCRIPTION
**Pull request by sjmiller609**
Closes: https://github.com/astronomer/issues/issues/1557

In summary, we would like to delete any pod that is older than X minutes and not at full container readiness

### CODE REVIEW

**Review by jpweber — APPROVED** [review]

**Comment by sjmiller609** [comment]
some difference in flake8 locally and in CI so give me a sec to sort that out

**Comment by sjmiller609** [comment]
ah ok. can reproduce locally after:
```
 pip install -e '.[test]
```

**Comment by sjmiller609** [comment]
I'll wait on @schnie 's review before merging because this one is a significant behavior change. This is still susceptible to the "namespace full" issue. Perhaps we might consider refactoring to loop across all airflow namespaces, then run this in the Astronomer namespace. That is out of scope for this change.

**Review by schnie — APPROVED** [review]
LGTM. I don't know what would cause these yet, but this seems fine

**Review by danielhoherd — APPROVED** [review]

**Comment by sjmiller609** [comment]
I will need to follow up by integrating this into AC. I'm going to leave this PR open so I remember to do that.

**Review by danielhoherd — APPROVED** [review]

**Pull request closed without merging**
